### ISSUE TITLE
Cloning repository error

### ISSUE THREAD

**Issue by Vilvarin** [charsheet-su/WOD-Mortal-charsheet#1]
The cloned project throws an error "Error loading useful things!" when I try to open project on a local server.

Error throws in init.js, function load_useful(). JQuery sends a ajax-request to js/useful.html, but it's not in project.

**Comment by jehy** [comment]
Hi! **js/useful.html** is a common part for all sheets - it provides instrumental panel with revisions, printing, comment and etc. That's why it was not found.

To make sure it does not mess with development, I added a check for development environment and this document won't be loaded any more - please update to the last version.

**Comment by jehy** [comment]
Кстати, можно и по-русски : )

**Comment by jehy** [comment]
Кстати, добавил немного инфы в описание.
